apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: bankapp-namespace
  labels:
    app: bankapp
  
spec:
  type: NodePort  # Changed to LoadBalancer
  selector:
    app: bankapp-deploy
  ports:
    - protocol: TCP
      port: 8080       # Expose on port 8080
      targetPort: 8080
      nodePort: 30776 # Target the app's port
