apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: bankapp-namespace
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://bankapp-ab.cefo7yhuwfxg.us-east-1.rds.amazonaws.com:3306/BankDB
  SPRING_DATASOURCE_USERNAME: admin
  MYSQL_DATABASE: BankDB
